dist: bionic
language: node_js
node_js:
  - 11
cache:
   directories:
     - node_modules
before_script:
  - npm install -g
script:
  - gitfolio build k4ustu3h
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
   branch: master
