dist: bionic
language: node_js
node_js:
  - 11
cache:
   directories:
     - node_modules
before_script:
  - npm install -g
script:
  - gitfolio build k4ustu3h --fork --theme dark --sort updated --twitter k4ustu3h_ --dribbble k4ustu3h --email k4ustu3h@gmail.com
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
   branch: master
