dist: bionic
language: node_js
node_js:
  - 11
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
before_script:
  - npm install -g
script:
  - npm run test
  - npm run prettier
after_success:
  - lhci autorun --upload.target=temporary-public-storage --staticDistDir=/home/travis/build/k4ustu3h/gitfolio/dist
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  cleanup: false
  edge: true # opt in to dpl v2
  local_dir: dist
  verbose: true
  fqdn: k4ustu3h.cf
