dist: bionic
language: node_js
node_js:
  - 11
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.3.x
before_script:
  - npm install -g
script:
  - npm run build
  - npm run prettier
after_success:
  - lhci autorun --upload.target=temporary-public-storage
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  cleanup: false
  edge: true # opt in to dpl v2
  local_dir: dist
  verbose: true
  fqdn: dylanh.dev # forcing run
